### ISSUE TITLE
Cannot run pg2sqlite.jar, ClassNotFoundException

### ISSUE THREAD

**Issue by karenlaw** [caiiiycuk/postgresql-to-sqlite#10]
java pg2sqlite.jar
Error: Could not find or load main class pg2sqlite.jar
Caused by: java.lang.ClassNotFoundException: pg2sqlite.jar

java --version
openjdk 19.0.1 2022-10-18

**Comment by caiiiycuk** [comment]
You should run it with -jar flag:
```
java -jar pg2sqlite.jar <args>
```
