### ISSUE TITLE
Column types absent in output database

### ISSUE THREAD

**Issue by ldesousa** [caiiiycuk/postgresql-to-sqlite#12]
The example below uses the same sample SQL code provided in #11. The tool completes without error, but in the resulting database columns have no type.

```bash
$ java -jar ~/bin/pg2sqlite/pg2sqlite.jar -d ./test.sql -o test.db -f true
11:32:12.967 [main] WARN  c.github.caiiiycuk.pg2sqlite.Config$ - You should set SQLITE_TMPDIR environment variable to control where sqlite stores temp files
11:32:12.977 [main] INFO  com.github.caiiiycuk.pg2sqlite.Boot$ - './test.sql' (0 Mb) -> 'test.db'
11:32:12.979 [main] INFO  c.g.c.pg2sqlite.LoggedIterator - Progress 100.0%, elapsed: 0m 0s 5ms / remaining: 0m 0s 0ms...	
11:32:13.644 [main] INFO  com.github.caiiiycuk.pg2sqlite.Boot$ - Well done...

$ sqlite3 test.db
SQLite version 3.37.2 2022-01-06 13:25:41
Enter ".help" for usage hints.
sqlite> SELECT typeof(client_id) FROM product;
sqlite>
```

**Comment by caiiiycuk** [comment]
**It's correct.** Sqlite3 is not "rigidly-typed database", from docs:

> SQL database engines that use rigid typing will usually try to automatically convert values to the appropriate datatype. Consider this:

    CREATE TABLE t1(a INT, b VARCHAR(10));
    INSERT INTO t1(a,b) VALUES('123',456);

> Rigidly-typed database will convert the string '123' into an integer 123 and the integer 456 into a string '456' prior to doing the insert.
> In order to maximize compatibility between SQLite and other database engines, and so that the example above will work on SQLite as it does on other SQL database engines, SQLite supports the concept of "type affinity" on columns. The type affinity of a column is the recommended type for data stored in that column. The important idea here is that the type is recommended, not required. Any column can still store any type of data. It is just that some columns, given the choice, will prefer to use one storage class over another. The preferred storage class for a column is called its "affinity". 


The idea of pg2sqlite is to create readonly database from postgresql dump, that contains same data that original dump. It is not intend to exactly clone the database.
