### ISSUE TITLE
Support for macOS arm64

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [caiiiycuk/postgresql-to-sqlite#15]
This looks precisely like what I want, but alas the sqlite library doesn't seem to support arm64. Any chance this could be updated?

**Comment by AaronRobinsonMSFT** [comment]
I updated the following to [`"3.42.0.0"`](https://github.com/xerial/sqlite-jdbc/releases/tag/3.42.0.0) and was able to build and run successfully.

https://github.com/caiiiycuk/postgresql-to-sqlite/blob/d41b9df8b5f83cc99c684b160f3d7d5f33b39afe/project/Build.scala#L16

I am hitting issue with my my `.sql` file but it does create the database. I assume any tests would catch issues if they exist. Happy to submit a PR if that is desired.

**Comment by caiiiycuk** [comment]
Hi. Yes please, any help would be greatly appreciated. What issue do you have?

**Comment by AaronRobinsonMSFT** [comment]
> Yes please, any help would be greatly appreciated. 

Will do.

> What issue do you have?

I think there are two and perhaps related.

1) If a line starts with "copy" it seems to be interpreted as a command. However in my case that line is merely a multi-line string in an `INSERT` clause. It looks like the tool doesn't track open/close `'` in all cases.

2) I was finally able to get the tool to complete successfully, and the tables were populated. All the tables seemed properly defined, but there was something amiss with the inserts.

**Comment by caiiiycuk** [comment]
@AaronRobinsonMSFT Hi, do you have any updates? Did you solve your problems?

**Comment by AaronRobinsonMSFT** [comment]
> @AaronRobinsonMSFT Hi, do you have any updates? Did you solve your problems?

@caiiiycuk I actually wasn't able to export the data in a way I could consume it easily in sqlite. However, I was able to properly update this so it would build and run on the macOS M1 platform. I've created a PR for updating to the version that allowed me to build and run on the M1 - https://github.com/caiiiycuk/postgresql-to-sqlite/pull/16.
