### ISSUE TITLE
0-byte file

### ISSUE THREAD

**Issue by Sugermaps** [caiiiycuk/postgresql-to-sqlite#22]
Hello, first of all, thank you very much for the tool. When I converted the file with the tool, it didn't prompt any errors and generated a 0-byte file. I'm a rookie and don't quite know what the problem is.
The specific order is:java -jar pg2sqlite-1.0.2.jar -d data1.dmp -o data.db

**Comment by caiiiycuk** [comment]
Hi, can you provide sample dump file to test?
