### ISSUE TITLE
Usage in Node Js

### ISSUE THREAD

**Issue by fwt-parth-jariwala** [caiiiycuk/postgresql-to-sqlite#24]
I have extracted zip file in my nodejs project and it has created a new directory in it. Now how can i use it to convert my postgres sql file to sqlite db conversion?

**Comment by caiiiycuk** [comment]
HI, as explaind in README file you need to run it with following arguments:

```
java -jar  pg2sqlite-1.0.3.jar -d database.dump -o sqlite.db
```

The way to run it is not related to Node.js. You should run it as a separate process, as an external program. In the end, it is executed on the JVM and does not know anything about Node.

**Comment by fwt-parth-jariwala** [comment]
I am runnig on ubuntu 20.04 and when i run command
java -jar  pg2sqlite-1.0.3.jar -d database.dump -o sqlite.db
it gives me error:command not found: java

**Comment by caiiiycuk** [comment]
Obviously you need to install java:
```
sudo apt install openjdk-21-jre
```

**Comment by fwt-parth-jariwala** [comment]
I have following java versionm
![image](https://github.com/caiiiycuk/postgresql-to-sqlite/assets/110459026/c8a10bba-9661-4b04-b98d-8c37738fe73f)

**Comment by caiiiycuk** [comment]
so then you can run pg2sqlite-1.0.3.jar

**Comment by fwt-parth-jariwala** [comment]
Can you tell me how can i run it node js?

**Comment by caiiiycuk** [comment]
> Can you tell me how can i run it node js?

https://stackoverflow.com/questions/20643470/execute-a-command-line-binary-with-node-js
