### ISSUE TITLE
Usage in Ubuntu

### ISSUE THREAD

**Issue by fwt-parth-jariwala** [caiiiycuk/postgresql-to-sqlite#25]
Hello,
Can you provide me a tutorial on how to use pg2sqlite in ubuntu 20.04, i have download zip file and extracted and in that directory when i run: pg2sqlite -d database.dump -o sqlite.db ,it gives me error:command not found: pg2sqlite.
![image](https://github.com/caiiiycuk/postgresql-to-sqlite/assets/110459026/0050c0d9-a260-48c5-ba63-99afb6d62f49)

**Comment by caiiiycuk** [comment]
* Install java on your PC
* Download jar file from [releases](https://github.com/caiiiycuk/postgresql-to-sqlite/releases/)
* Run it like this:
```
java -jar pg2sqlite-1.0.3.jar ...
```

**Comment by fwt-parth-jariwala** [comment]
Now i am able to create database but it does not include any data type or constraints for columns of table. How can i do  it?

**Comment by caiiiycuk** [comment]
sqlite does not support types, all fields in sqlite are strings https://www.sqlite.org/datatype3.html
