### ISSUE TITLE
Empty output file

### ISSUE THREAD

**Issue by hilburn** [caiiiycuk/postgresql-to-sqlite#29]
I saw this issue a couple of times in closed issues but yeah - trying to convert over from Home Assistant in postgresql back to sqlite (old NAS container HA defaulted to postgresql and I don't want to lose a year's worth of data)

![image](https://github.com/user-attachments/assets/77495a4c-6d1e-4913-a8e4-affed1e72078)

Has same result from both the zipped and unzipped versions of the file

If you need the dumped file to debug I can send it over, though as it's a) large and b) contains some personal information (like phone tracking data) it'd have to be non-public

**Comment by caiiiycuk** [comment]
If possible please send a part of it, actually I think couple rows are enough cause result is empty

**Comment by hilburn** [comment]
Which parts are useful? I'm afraid I don't know much about databases...

**Comment by hilburn** [comment]
I'm going to close this as I found out the issue, the script the NAS was using for dumping the database was using a weird binary formatting that, in fairness, massively shrunk the size of the file (when I removed it the size went from 140MB to 1GB+), but completely makes sense why this wasn't able to parse it given it's non-standard!
Also explains my confusion when the instructions I read were like "just go in and change XYZ" and I can't tell heads from tails, let alone unique ids from INSERT INTO commands

**Comment by caiiiycuk** [comment]
Great to  know! Thank you
