### ISSUE TITLE
binary data in strings isn't supported

### ISSUE THREAD

**Issue by pklapperich** [caiiiycuk/postgresql-to-sqlite#6]
in the output from `pg_dump`, a text field containing binary data will start with `\\x` followed by a hex encoded copy of the binary data. Ex:
```
COPY "user" (id, session, remote_id, user_agent) FROM stdin;
12    \\x80059519040000000000008c0c68747470     259087435        user_agent string
\.
```

After running `pg2sqlite`, the sqlite database has the literal string `\x80059519040000000000008c0c68747470`, when it should contain actual binary data.

**Comment by caiiiycuk** [comment]
Actually pg2sqlite supports binary data, but only in hex format. Can you check please?
