### ISSUE TITLE
Getting unknown database public error while trying to convert PostgreSQL database backup to sqlite

### ISSUE THREAD

**Issue by asharabu** [caiiiycuk/postgresql-to-sqlite#8]
Hi,
Getting unknown database public error while trying to convert PostgreSQL database backup to sqlite

> 
======
postgresql-to-sqlite# ./pg2sqlite.jar -d database-19-01-2021-09.bak -o database-sqlite.db
04:46:43.600 [main] WARN  c.github.caiiiycuk.pg2sqlite.Config$ - You should set SQLITE_TMPDIR environment variable to control where sqlite stores temp files
04:46:43.608 [main] INFO  com.github.caiiiycuk.pg2sqlite.Boot$ - 'database-19-01-2021-09.bak' (132 Mb) -> 'database-sqlite.db'
04:46:44.090 [main] ERROR com.github.caiiiycuk.pg2sqlite.Boot$ -
Create Table - Exception:
        unknown database public
        [SQL] 'CREATE TABLE public.announcements ([id], [text], [show_until], [active], [created_at], [updated_at]);'
        [LINE #56] CREATE TABLE public.announcements (     id integer NOT NULL,     text text,     show_until date,     active boolean DEFAULT false,     created_at timestamp without time zone,     updated_at timestamp without time zone );,

04:46:44.090 [main] ERROR com.github.caiiiycuk.pg2sqlite.Boot$ - Task failed.

======

**Comment by caiiiycuk** [comment]
Try this:
```
$ pg_dump postgres://{USER}:{PASS}@localhost/{DATABASE} -f output.dump
$ sed 's/public\.//' -i  output.dump
$ pg2sqlite -d output.dump -o sqlite.db
```

from #2

**Comment by asharabu** [comment]
Hi,
Thanks for your quick reply.
It got fixed. But now we are getting another error

> 

============

05:58:03.378 [main] ERROR com.github.caiiiycuk.pg2sqlite.Boot$ -
Create Index - Exception:
        near "(": syntax error
        [SQL] 'CREATE INDEX index_background_migration_jobs_for_partitioning_migrations ON background_migration_jobs (((arguments)'
        [LINE #342829] CREATE INDEX index_background_migration_jobs_for_partitioning_migrations ON background_migration_jobs USING btree (((arguments ->> 2))) WHERE (class_name = 'Gitlab::Database::PartitioningMigrationHelpers::BackfillPartitionedTable'::text);,

05:58:03.530 [main] ERROR com.github.caiiiycuk.pg2sqlite.Boot$ - Task failed..

======

**Comment by caiiiycuk** [comment]
Do you need index creation? Try to delete them from dump file
